# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a18f8dc58e62fb110e3d1b8b72fe31d56440799150ef9ea7eb95f4b40ec3e4728da07b7fdf3c6f121843573e05f2137537c1a538fe58f894d76d349e3b415590

test:
  secret_key_base: e3e6bd7e90503f59057f47b6c35864f47ef4455adbbd16c64331034b58cd39615078cf739c0153e5a6534b8b28e2fcc4461f1c0c9e430c74db13eed3afc6e022

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
